version: '3.8'
services:
  db:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: mentor
      POSTGRES_USER: mentor
      POSTGRES_PASSWORD: mentor
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
